- name: My first play
  hosts: localhost
  become: true
  vars_prompt:
    - name: git_name
      prompt: What name will be used for git?
      private: false

    - name: git_email
      prompt: What email will be used for git?
      private: false
  vars:
    greeting: "Hello"
  tasks:
    - name: Install zsh
      apt: name=zsh
    - name: Change shell
      shell: chsh -s `which zsh`
    - name: Install ohmyzsh 
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    - name: Print a greeting message
      debug:
        msg: "{{ greeting }} {{ git_name }} {{ git_email }}"

# Tasks that should be added
# 1.
      #
